[2024-05-18T15:43:36.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T15:43:36.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson_ingestion.is_api_available manual__2024-05-18T15:43:33.393171+00:00 [queued]>
[2024-05-18T15:43:36.376+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson_ingestion.is_api_available manual__2024-05-18T15:43:33.393171+00:00 [queued]>
[2024-05-18T15:43:36.377+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-18T15:43:36.445+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-05-18 15:43:33.393171+00:00
[2024-05-18T15:43:36.455+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1058) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T15:43:36.457+0000] {standard_task_runner.py:63} INFO - Started process 1062 to run task
[2024-05-18T15:43:36.457+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson_ingestion', 'is_api_available', 'manual__2024-05-18T15:43:33.393171+00:00', '--job-id', '1163', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_ingestion.py', '--cfg-path', '/tmp/tmp2b8bkbe_']
[2024-05-18T15:43:36.461+0000] {standard_task_runner.py:91} INFO - Job 1163: Subtask is_api_available
[2024-05-18T15:43:36.547+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson_ingestion.is_api_available manual__2024-05-18T15:43:33.393171+00:00 [running]> on host 8d1d9b6df744
[2024-05-18T15:43:36.722+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson_ingestion' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T15:43:33.393171+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T15:43:33.393171+00:00'
[2024-05-18T15:43:36.725+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T15:43:36.726+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-18T15:43:36.727+0000] {http.py:137} INFO - Poking: /users/
[2024-05-18T15:43:36.741+0000] {base.py:84} INFO - Using connection ID 'dummyjson_api' for task execution.
[2024-05-18T15:43:38.006+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-18T15:43:38.008+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T15:43:38.029+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dummyjson_ingestion, task_id=is_api_available, run_id=manual__2024-05-18T15:43:33.393171+00:00, execution_date=20240518T154333, start_date=20240518T154336, end_date=20240518T154338
[2024-05-18T15:43:38.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T15:43:38.104+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T15:43:38.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
