[2024-05-19T15:23:07.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T15:23:07.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson.is_user_api_available scheduled__2024-05-17T17:00:00+00:00 [queued]>
[2024-05-19T15:23:07.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson.is_user_api_available scheduled__2024-05-17T17:00:00+00:00 [queued]>
[2024-05-19T15:23:07.950+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-05-19T15:23:07.994+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_user_api_available> on 2024-05-17 17:00:00+00:00
[2024-05-19T15:23:08.008+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1682) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T15:23:08.012+0000] {standard_task_runner.py:63} INFO - Started process 1692 to run task
[2024-05-19T15:23:08.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson', 'is_user_api_available', 'scheduled__2024-05-17T17:00:00+00:00', '--job-id', '2006', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson.py', '--cfg-path', '/tmp/tmpqqwq6aew']
[2024-05-19T15:23:08.015+0000] {standard_task_runner.py:91} INFO - Job 2006: Subtask is_user_api_available
[2024-05-19T15:23:08.142+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson.is_user_api_available scheduled__2024-05-17T17:00:00+00:00 [running]> on host ca927d78a9ea
[2024-05-19T15:23:09.029+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson' AIRFLOW_CTX_TASK_ID='is_user_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T17:00:00+00:00'
[2024-05-19T15:23:09.030+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T15:23:09.031+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-19T15:23:09.032+0000] {http.py:137} INFO - Poking: /users/
[2024-05-19T15:23:09.055+0000] {base.py:84} INFO - Using connection ID 'dummyjson_api' for task execution.
[2024-05-19T15:23:10.899+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-19T15:23:10.902+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T15:23:10.963+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dummyjson, task_id=is_user_api_available, run_id=scheduled__2024-05-17T17:00:00+00:00, execution_date=20240517T170000, start_date=20240519T152307, end_date=20240519T152310
[2024-05-19T15:23:11.404+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T15:23:11.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
