[2024-05-16T09:27:08.268+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T09:27:08.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T01:00:00+00:00 [queued]>
[2024-05-16T09:27:08.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T01:00:00+00:00 [queued]>
[2024-05-16T09:27:08.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-16T09:27:08.690+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-05-01 01:00:00+00:00
[2024-05-16T09:27:08.760+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T09:27:08.785+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2024-05-16T09:27:08.782+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'randomuser_ingestion', 'is_api_available', 'scheduled__2024-05-01T01:00:00+00:00', '--job-id', '1011', '--raw', '--subdir', 'DAGS_FOLDER/randomuser_ingestion.py', '--cfg-path', '/tmp/tmpdsc9tnyl']
[2024-05-16T09:27:08.794+0000] {standard_task_runner.py:91} INFO - Job 1011: Subtask is_api_available
[2024-05-16T09:27:09.355+0000] {task_command.py:426} INFO - Running <TaskInstance: randomuser_ingestion.is_api_available scheduled__2024-05-01T01:00:00+00:00 [running]> on host 8d1d9b6df744
[2024-05-16T09:27:09.975+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='randomuser_ingestion' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T01:00:00+00:00'
[2024-05-16T09:27:09.981+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T09:27:09.990+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-05-16T09:27:10.000+0000] {http.py:137} INFO - Poking: /api
[2024-05-16T09:27:10.040+0000] {base.py:84} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-05-16T09:27:12.821+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-05-16T09:27:12.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T09:27:12.846+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=randomuser_ingestion, task_id=is_api_available, run_id=scheduled__2024-05-01T01:00:00+00:00, execution_date=20240501T010000, start_date=20240516T092708, end_date=20240516T092712
[2024-05-16T09:27:13.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T09:27:13.151+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T09:27:13.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
